[build]
  command = "npm install && npm run build"
  publish = "dist"

# (Optional but recommended) lock Node for consistent builds
[build.environment]
  NODE_VERSION = "20"

# Proxy API to Render
[[redirects]]
  from = "/api/*"
  to = "https://backend-test-xfo3.onrender.com/api/:splat"
  status = 200
  force = true

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
