[build]
 
  command = "npm ci && npm run build"
  publish = "dist"

# Proxy API to your Render backend
[[redirects]]
  from = "/api/*"
  to = "https://backend-test-xfo3.onrender.com/api/:splat"
  status = 200
  force = true

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
