[build]
  base = "frontend"
  command = "npm ci && npm run build"
  publish = "dist"

# Proxy all /api/* calls to your Render backend
[[redirects]]
  from = "/api/*"
  to = "https://backend-test-xfo3.onrender.com/api/:splat"
  status = 200
  force = true

# Single Page App fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
