[build]
  command = "npm run build"
  publish = "dist"

# Proxy API to your Render backend
[[redirects]]
  from = "/api/*"
  to = "https://backend-test-3-73cu.onrender.com/api/:splat"
  status = 200
  force = true

# Single-page app fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
